modeling: 
# variables expected to materially alter model performance

  # defining the modeling period
  training_period_start: '2024-01-01'
  training_period_end: '2024-06-30'
  modeling_period_start: '2024-07-01'
  modeling_period_end: '2024-7-31'

  # defining target variable thresholds
  moon_threshold: 0.3  # 30% increase
  dump_threshold: -0.2  # 20% decrease

  # shark identification parameters
  shark_minimum_inflows: 15000  # Minimum amount of USD inflows to be considered a shark
  shark_total_profits_threshold: 20000  # Lifetime absolute USD return threshold for sharks
  shark_total_return_threshold: 0.2  # Lifetime percentage return threshold for sharks

  # megashark thresholds
  shark_wallet_type: 'is_returns_shark'
  shark_wallet_min_coins: 3
  shark_wallet_min_shark_rate: 0.4

data_cleaning:
# variables used to clean and filter raw data before training data is built

  # profits_df filters
  # the goal of these is to remove CEX wallets that don't belong in the dataset
  profitability_filter: 500000000000  # Exclude wallets with more than x profits or losses
  inflows_filter: 10000000  # Exclude wallets with more than x inflows

  # prices_df filters
  max_gap_days: 2  # Maximum consecutive missing days to fill in price gaps
