modeling: 
# variables expected to materially alter model performance

  # defining the modeling period
  modeling_period_start: '2024-03-01'
  modeling_period_end: '2024-03-31'

  # defining target variable thresholds
  moon_threshold: 0.3  # 30% increase
  dump_threshold: -0.2  # 20% decrease

  # shark identification parameters
  balance_threshold: 10000  # Minimum balance to be considered a shark
  profitability_threshold: 50000  # Lifetime profitability threshold for sharks

data_cleaning:
# variables used to clean and filter raw data before training data is built
  profitability_filter: 10000000  # Exclude wallets with more than $10m profits or losses
  max_gap_days: 2  # Maximum consecutive missing days to fill in price gaps
