metrics:
  buyers_new:
    aggregations:   # Defines core aggregations
      - "sum"
      - "mean"
      - "median"
      - "std"
    rolling:        # Rolling stats: combine them under one block for each metric
      stats:        # Specify which summary stats need rolling
        - "sum"
        - "max"
      comparisons: 
        - "change"
        - "pct_change"
      window_duration: 7    # Days per rolling window
      lookback_periods: 8   # How many lookback periods