# This experiment config file defines parameter variations for running experiments
# across multiple configurations. It is linked to three main config files:
# - config.yaml: Contains settings for training data, wallet cohorts, and data cleaning.
# - modeling_config.yaml: Contains preprocessing steps and modeling-related parameters.
# - metrics_config.yaml: Defines metrics and their aggregations for evaluation.

metadata:
  experiment_name: "0926_whal_cohort_cutoffs"
  search_method: "random"
  description: "Experiment to assess potential whale cohort cutoffs."
  metrics_to_compare:
    - roc_auc
  # thresholds: [0.5, 0.6, 0.7]
  max_evals: 100

variable_overrides:
  config:
    datasets:
      wallet_cohorts:
        whales:
          wallet_minimum_inflows: [50000,100000,250000,500000]
          wallet_maximum_inflows: [600000,1000000,2000000,5000000]
          coin_return_win_threshold: [0.1,0.2,0.35]
          wallet_min_coin_wins: [1,2,3]

  modeling_config:
  #   preprocessing:
  #     drop_features:
  #       - ['total_sellers_sum', 'buyers_new_median']  # Drop these two features
  #       - ['total_sellers_sum']  # Drop only one feature for comparison

    target_variables:
      moon_threshold: [0.1,0.2,0.3]
    # modeling:
    #   model_params:
    #     n_estimators:
    #       - 50  # Number of trees in the model
    #       - 100  # Number of trees in the model


  # metrics_config:
  #   wallet_cohorts:
  #     whales:
  #       buyers_new:
  #         aggregations:
  #           sum:
  #             scaling: ["log","none"]
  #         rolling:
  #           aggregations:
  #             sum:
  #               scaling: "log"
  #           window_duration: [5,10,15]
  #           lookback_periods: 3
  #       total_bought:
  #         aggregations:
  #           sum:
  #             scaling: ["log","none"]
  #         rolling:
  #           aggregations:
  #             sum:
  #               scaling: ["log","none"]
  #           window_duration: [5,10,15]
  #           lookback_periods: 3
  #       total_sold:


  # # Time series keyed on coin_id-date
  # time_series:
  #   market_data:
  #     price:
  #       rolling:
  #         window_duration: [5,10,15]
  #     volume:
  #       rolling:
  #         aggregations:
  #           sum:
  #             scaling: ["log","none"]
  #         window_duration: [5,10,15]
