investing_epochs: [
# Long term validation of how well this model's predictions perform
#  over epochs starting in [30,60,90] days.
    30,
    60,
    90,
    # 120,
    # 150,
    # 180,
    # 210,
    # 240,
    # 270,
    # 300,
    # 330,
    # 360,
    # 390,
    # 420,
    # 450,
    # 480,
    # 510,
    # 540,
    # 570,
    # 600
]

training_data:
    toggle_overwrite_parquet: False  # determines whether to load preexisting training_data_dfs

# Params that define trading strategy
trading:
    score_threshold: 0.8  # What is considered a "high score" for buy decisions
    min_scores: 15  # How many "high scores" a coin should have to be bought


n_threads:
    investing_epochs: 4  # how many investing epochs are calculated concurrently