investing_epochs: [
# Long term validation of how well this model's predictions perform
#  over epochs starting in [30,60,90] days.
    60,
    120,
    180,
    240,
    300,
    360,
    420,
    # 480,
    # 540,
    # 600

    # 30,
    # 90,
    # 150,
    # 210,
    # 270,
    # 330,
    # 390,
    # 450,
    # 510,
    # 570,
]

training_data:
    toggle_overwrite_parquet: True  # determines whether to load preexisting training_data_dfs
    # toggle_overwrite_parquet: False  # determines whether to load preexisting training_data_dfs

# Params that define trading strategy
trading:
    high_score_threshold: 0.55  # What is considered a "high score" for buy decisions
    min_high_scores: 20  # How many "high scores" a coin should have to be bought
    min_average_score: 0.20  # The minimum average score for a coin to be included
    max_coins_per_epoch: 10  # only this number of coins will be bought, sorted by mean score


n_threads:
    investing_epochs: 6  # how many investing epochs are calculated concurrently
    buy_logic_epochs: 6  # how many epoch buys to choose based on scores