investing_epochs: [
# Long term validation of how well this model's predictions perform
#  over epochs starting in [30,60,90] days.
    60,
    120,
    180,
    # 240,
    # 300,
    # 360,
    # 30,
    # 90,
    # 150,
    # 210,
    # 270,
    # 330,
    # 390,
    # 420,
    # 450,
    # 480,
    # 510,
    # 540,
    # 570,
    # 600
]

training_data:
    toggle_overwrite_parquet: True  # determines whether to load preexisting training_data_dfs
    # toggle_overwrite_parquet: False  # determines whether to load preexisting training_data_dfs

# Params that define trading strategy
trading:
    score_threshold: 0.95  # What is considered a "high score" for buy decisions
    min_scores: 25  # How many "high scores" a coin should have to be bought
    max_coins_per_epoch:  5  # only this number of coins will be bought, sorted by mean score


n_threads:
    investing_epochs: 6  # how many investing epochs are calculated concurrently
    buy_logic_epochs: 6  # how many epoch buys to choose based on scores