# Available Commands:
# aggregations:
#   - "sum", "mean", "median", "min", "max", "std"
# rolling stats:
#   - "sum", "mean", "median", "max", "min", "std"
# comparisons:
#   - "change", "pct_change", "difference"
# window_duration:
#   - Specifies the number of days per rolling window (e.g., 7 means a 7-day rolling window)
# lookback_periods:
#   - Defines how many periods to look back when calculating rolling stats (e.g., 8 means calculate rolling stats over 8 previous periods)

metrics:
  sharks:
    buyers_new:
      aggregations:
        sum:
          scaling: "standard"    # Scaling applied to sums, which can vary significantly in range.
        mean:
          scaling: "minmax"      # Scaling for mean to normalize values between 0 and 1.
        std:
          scaling: "standard"    # Standard scaling for standard deviation to account for variability.
        median:                  # No scaling specified here
          scaling: "none"        # No scaling for percentage change, as it's already normalized.

      rolling:
        stats:
          sum:
            scaling: "minmax"
          max:
            scaling: "standard"
        comparisons:
          change:
            scaling: "standard"
          pct_change:
            scaling: "none"        # No scaling for percentage change, as it's already normalized.
        window_duration: 14
        lookback_periods: 4

    total_bought:
      aggregations:
        sum:
          scaling: "standard"    # Large sums of total bought should be scaled to avoid model distortion.
        median:
      rolling:
        stats:
          sum:
            scaling: "minmax"
        comparisons:
          change:
            scaling: "standard"
        window_duration: 14
        lookback_periods: 4

    total_sold:
      aggregations:
        sum:
          scaling: "standard"    # Total sold should also be scaled to account for high variance.

    total_buyers:
      aggregations:
        sum:
    sellers_new:
      aggregations:
        sum:
          scaling: "standard"
        mean:
          scaling: "standard"
        median:
    buyers_repeat:
      aggregations:
        sum:
          scaling: "standard"
        mean:
          scaling: "standard"
        median:
  prices:
    price:
      aggregations:
        max:
          scaling: "standard"
    rolling:
        stats:
          sum:
            scaling: "minmax"
          max:
            scaling: "standard"
        comparisons:
          pct_change:
            scaling: "none"        # No scaling for percentage change, as it's already normalized.
        window_duration: 14
        lookback_periods: 4
