# See details on config structure and valid inputs in src/config_models/metrics_config.py

# Time series keyed on coin_id-date
time_series:
    market_data:
        price:
            indicators:
                ema:
                    parameters:
                        window: [7]
                    rolling:
                        comparisons:
                            pct_change:
                                scaling: "none"
                        window_duration: 5
                        lookback_periods: 4
                # sma:
                #     parameters:
                #         window: [30]
                #     rolling:
                #         comparisons:
                #             pct_change:
                #                 scaling: "none"
                #         window_duration: 5
                #         lookback_periods: 4
                rsi:
                    parameters:
                        window: [14]
                    aggregations:
                        last:
                            scaling: "none"
                        first:
                            scaling: "none"
        volume:
            rolling:
                aggregations:
                    sum:
                        scaling: "none"
                window_duration: 5
                lookback_periods: 4
        market_cap:
            aggregations:
                last:
                    scaling: "none"
        mfi:
            aggregations:
                last:
                    scaling: "none"
        obv:
            aggregations:
                last:
                    scaling: "none"

# Keyed on coin_id-date
wallet_cohorts:
    # whales_longterm:
    #     buyers_new:
    #         aggregations:
    #             sum:
    #                 scaling: "none"
    #     buyers_repeat:
    #         rolling:
    #             aggregations:
    #                 sum:
    #                     scaling: "none"
    #             window_duration: 5
    #             lookback_periods: 4
    #     total_bought:
    #         rolling:
    #             aggregations:
    #                 sum:
    #                     scaling: "none"
    #             window_duration: 5
    #             lookback_periods: 4
    #     total_balance:
    #         rolling:
    #             aggregations:
    #                 last:
    #                     scaling: "none"
    #             window_duration: 5
    #             lookback_periods: 4
    whales:
        buyers_new:
            aggregations:
                sum:
                    scaling: "none"
        buyers_repeat:
            rolling:
                aggregations:
                    sum:
                        scaling: "none"
                window_duration: 15
                lookback_periods: 2
        total_bought:
            rolling:
                aggregations:
                    sum:
                        scaling: "none"
                window_duration: 15
                lookback_periods: 2
        total_balance:
            rolling:
                aggregations:
                    last:
                        scaling: "none"
                window_duration: 15
                lookback_periods: 2

    # normies:
    #     buyers_new:
    #         rolling:
    #             aggregations:
    #                 sum:
    #                     scaling: "none"
    #             window_duration: 15
    #             lookback_periods: 2
    #     total_holders:
    #         rolling:
    #             aggregations:
    #                 last:
    #                     scaling: "none"
    #             window_duration: 15
    #             lookback_periods: 2
    #     total_bought:
    #         rolling:
    #             aggregations:
    #                 sum:
    #                     scaling: "none"
    #             window_duration: 15
    #             lookback_periods: 2
    #     total_sold:
    #         rolling:
    #             aggregations:
    #                 sum:
    #                     scaling: "none"
    #             window_duration: 15
    #             lookback_periods: 2
    #     total_balance:
    #         rolling:
    #             aggregations:
    #                 last:
    #                     scaling: "none"
    #             window_duration: 15
    #             lookback_periods: 2

    # midtier:
    #     buyers_new:
    #         rolling:
    #             aggregations:
    #                 sum:
    #                     scaling: "none"
    #             window_duration: 5
    #             lookback_periods: 4
    #     total_holders:
    #         rolling:
    #             aggregations:
    #                 last:
    #                     scaling: "none"
    #             window_duration: 5
    #             lookback_periods: 4
    #     total_bought:
    #         rolling:
    #             aggregations:
    #                 sum:
    #                     scaling: "none"
    #             window_duration: 5
    #             lookback_periods: 4
    #     total_sold:
    #         rolling:
    #             aggregations:
    #                 sum:
    #                     scaling: "none"
    #             window_duration: 5
    #             lookback_periods: 4
    #     total_balance:
    #         rolling:
    #             aggregations:
    #                 last:
    #                     scaling: "none"
    #             window_duration: 5
    #             lookback_periods: 4


# Time series keyed on only date
macro_trends:

    # gtrends_cryptocurrency_worldwide:
    #     aggregations:
    #         last:
    #             scaling: "none"
    # btc_mvrv_z_score:
    #     aggregations:
    #         last:
    #             scaling: "none"
    # global_volume:
    #     rolling:
    #         aggregations:
    #             sum:
    #                 scaling: "none"
    #         window_duration: 15
    #         lookback_periods: 2
    # btc_price:
    #     indicators:
    #         ema:
    #             parameters:
    #                 window: [7]
    #             rolling:
    #                 comparisons:
    #                     pct_change:
    #                         scaling: "none"
    #                 window_duration: 15
    #                 lookback_periods: 2
    #         rsi:
    #             parameters:
    #                 window: [14]
    #             aggregations:
    #                 last:
    #                     scaling: "none"
    # global_market_cap:
    #     indicators:
    #         rsi:
    #             parameters:
    #                 window: [14]
    #             aggregations:
    #                 last:
    #                     scaling: "none"
    #             aggregations:
    #                 first:
    #                     scaling: "none"
