preprocessing:
  drop_features:  # List of features to drop from the dataset before modeling

target_variables: 
  moon_threshold: 0.15  # Target for a 'moon' event, defined as a 30% price increase
  crater_threshold: -0.2  # Target for a 'crater' event, defined as a 20% price decrease

modeling:
  target_column: "is_moon"  # or "is_crater" depending on the experiment
  modeling_folder: "..//modeling"  # location of the modeling folder where outputs will be saved
