# See details on config structure and valid inputs in src/config_models/metrics_config.py

# Time series keyed on coin_id-date
time_series:
    market_data:
        price:
            indicators:
                sma:
                    parameters:
                        window: [5]
                rsi:
                    parameters:
                        window: [5]
        volume:
            indicators:
                sma:
                    parameters:
                        window: [5]
        mfi:
            indicators:
                sma:
                    parameters:
                        window: [5]
        obv:
            indicators:
                sma:
                    parameters:
                        window: [5]

# # Time series keyed on only date
# macro_trends:
#     global_market_cap:
#         indicators:
#             rsi:
#                 parameters:
#                     window: [14]
