# CheckpointValidation
# WalletModel Config
# Time series keyed on coin_id-date
time_series:
    market_data:
        price:
            indicators:
                sma:
                    parameters:
                        window: [2]
                # rsi:
                #     parameters:
                #         window: [7]
        volume:
            indicators:
                sma:
                    parameters:
                        window: [12]
        # mfi:
        #     indicators:
        #         sma:
        #             parameters:
        #                 window: [5]
        # obv:
        #     indicators:
        #         sma:
        #             parameters:
        #                 window: [5]
