# CheckpointValidation
# WalletModel Config
market_timing:
  offsets:
    price_sma_2:
      offsets: [-30,-15]
      retain_base_columns: False
    volume_sma_12:
      offsets: [-21,21]
      retain_base_columns: False
