# Variables used to define the training data
training_data:
    training_window_starts: [
        # "2023-10-01",
        "2024-04-01",
        "2024-08-01",
    ]
    # modeling_period_start: "2024-02-01"
    # modeling_period_end: "2024-03-31"
    modeling_period_start: "2024-11-01"
    modeling_period_end: "2024-11-30"
    validation_period_end: "2024-12-07"


# Variables used to define features
features:
    timing_metrics_min_transaction_size: 20  # trades below this USD threshold will not be evaluated for market timing peformance


# Variables used to clean and filter raw data before training data is built
data_cleaning:

    # Modeling period filters
    min_modeling_investment: 2000
    min_modeling_transaction_days: 2

    # Wallet cohort thresholds
    min_coins_traded: 3  # Exclude wallets that have traded fewer coins than this during the training period
    max_coins_traded: 50  # Exclude wallets that have traded more coins than this during the training period
    min_wallet_investment: 50000 # The amount of lifetime USD investment a wallet must have to be included in the training data
    max_wallet_investment: 25_000_000 # The amount of lifetime USD investment a wallet must have to be included in the training data
    min_wallet_volume: 75000  # Exclude wallets with fewer than this amount of training period USD volume
    max_wallet_volume: 40_000_000  # Exclude wallets with fewer than this amount of training period USD volume
    max_wallet_profits: 25_000_000  # Exclude wallets with more than this total net gain from analysis

    # Coin-wallet pair thresholds
    max_wallet_coin_profits: 15000000  # Exclude wallets with profits or losses greater than or equal to this amount (USD)
    max_wallet_coin_inflows: 15000000  # Exclude wallets with inflows greater than or equal to this amount (USD)
    min_wallet_coin_inflows: 5000 # The amount of lifetime USD inflows a wallet must have to be included in the training data

    # Market data filters
    max_initial_market_cap: 100000_000_000  # coins above this market cap as of the start of the training period will be removed from all datasets
    max_gap_days: 50  # Maximum consecutive missing days to fill in price gaps (e.g., price interpolation for gaps up to 2 days)
    min_daily_volume: 5000 # Minimum average daily volume the coin must have

    # Market cap imputation filters
    min_mc_imputation_coverage: 0.3  # coins with market cap coverage below this level will have hardcoded market cap values filled
    max_mc_imputation_multiple: 2.0  # don't impute dates where the imputed market cap exceeds the max known market cap * this ratio
    market_cap_default_fill:  500000  # coins below the imputation coverage level will have empty values filled with this

    # Offset calculation limits
    offset_winsorization: 0.01 # comparisons between metrics and their offset values will be winsorized by this amount


# Variables used for comnverting the wallet scores into coin forecasts
coin_forecasting:

    # Forecasting methods
    top_n: 10  # how many of the top coins of a given sort method will be included in performance assessments
    sort_method: "top_wallet_balance_pct"  # which coin wallet metric to use for coin forecast rankings

    # Thresholds for coin inclusion in forecasts
    min_wallets: 5  # how many wallets must hold a coin for the coin to be elegible for forecasting
    min_balance: 10000  # how much USD all wallets must hold for the coin to be elegible for forecasting
    min_market_cap: 2_000_000  # coins below this market cap will not be included in performance assessments
    max_market_cap: 30_000_000  # coins above this market cap will not be included in performance assessments


# Variables used for model generation
modeling:
    target_variable: "performance_score"
    returns_winsorization: 0.01
    drop_columns: [
    ]
