# CheckpointValidation
# WalletModel Config
market_timing:
    offsets:
        price_sma_2:
            offsets: [-200, -60, -30, -15, 100]
            retain_base_columns: False
        volume_sma_12:
            offsets: [-80, -21, 21, 100]
            retain_base_columns: False
        global_volume:
            offsets: [-100, -50, -21, 21, 50, 100]
            retain_base_columns: False
        global_volume:
            offsets: [-100, -50, -21, 21, 50, 100]
            retain_base_columns: False
