# CoinModel Config

training_data: #CoinModel

    dataset: dev  # Set to prod or dev; determines whether to query core or dev dataset tables
    parquet_folder: temp/coin_modeling_dfs/dda749_clusters_v2

# CoinModel Cleaning
# Variables used to clean and filter raw data before training data is built
data_cleaning: #CoinModel

    # Market data filters
    max_initial_market_cap: 999150_000_000  # coins above this market cap as of the start of the training period will be removed from all datasets
    max_gap_days: 30  # Maximum consecutive missing days to fill in price gaps (e.g., price interpolation for gaps up to 2 days)
    min_daily_volume: 500 # Minimum average daily volume the coin must have


# CoinModel Wallet Scores
wallet_scores: #CoinModel

    #KeyParam Scores to include as segments + metrics
    score_params:
        # Return Rate
        cw_return_rate_000:
            target_variable: cw_crypto_net_gain/max_investment/base
            target_var_class_threshold: 0.00
            y_pred_threshold: 0.4

        cw_return_rate_005:
            target_variable: cw_crypto_net_gain/max_investment/base
            target_var_class_threshold: 0.05
            y_pred_threshold: 0.6

        cw_return_rate_025:
            target_variable: cw_crypto_net_gain/max_investment/base
            target_var_class_threshold: .25
            y_pred_threshold: 0.6

        cw_return_rate_040:
            target_variable: cw_crypto_net_gain/max_investment/base
            target_var_class_threshold: .40
            y_pred_threshold: 0.6

        cw_return_rate_regression:
            model_type: regression
            target_variable: cw_crypto_net_gain/max_investment/winsorized

        return_rate_regression:
            model_type: regression
            target_variable: crypto_net_gain/max_investment/winsorized

        # USD Metrics
        net_gain_1000:
            target_variable: crypto_net_gain
            target_var_class_threshold: 1000
            y_pred_threshold: 0.7

        cw_net_flows_1000:
            target_variable: cw_crypto_net_flows
            target_var_class_threshold: 1000
            y_pred_threshold: 0.7


# CoinModel Segments
wallet_segments: #CoinModel


    wallet_scores_binary_segments: True
    wallet_scores_residuals_segments: False
    wallet_scores_confidence_segments: False

    # score_segment_quantiles: [0.95]  # higher is better; how to assign wallet a score segment
    # score_segment_quantiles: [0.15, 0.85]  # higher is better; how to assign wallet a score segment

    training_period_cluster_groups: [5]  # which n clusters assignment from the training period to segment by


# CoinModel Features
wallet_features: #CoinModel

    # Features from the feature_engineering directory
    toggle_prior_model_features: False

    # Score features params
    usd_materiality: 20 # Wallets with volume/balances below this won't be counted in medians/distributions/etc

    # Metrics to drop based on low observed importance
    drop_trading_metrics: [
        crypto_cash_buys,
        crypto_cash_sells,
        crypto_inflows,
        crypto_net_cash_flows,
        crypto_net_flows,
        crypto_net_gain,
        crypto_outflows,
        max_investment,
        # total_volume,
        unique_coins_traded,
        # average_transaction,
    ]


# CoinModel Modeling Config
# Variables used in the generation of the validation period coin model
coin_modeling: #CoinModel

    #KeyParam Model Type
    # Target variable parameters
    # model_type: regression  # "regression" or "classification"
    model_type: classification  # "regression" or "classification"

    #KeyParam Target Variable
    target_variable: coin_return_winsorized
    # target_variable: coin_return
    # target_variable: coin_return_pctile_full
    # target_variable: coin_return_pctile
    target_var_class_threshold: 0.3  # a classification model will try to predict the target var above this value
    y_pred_threshold: 0.2  # scores above this probability threshold are positive predictions

    returns_winsorization: 0.005


    #KeyParam Modeling Cohort Definition
    # Thresholds for coin inclusion in training data
    min_cohort_wallets: 15  # how many wallets must hold a coin for the coin to be elegible for forecasting
    min_cohort_balance: 1000  # how much USD all wallets must hold for the coin to be elegible for forecasting

    # Thresholds for coin inclusion in training data
    min_market_cap: 000_000  # coins below this market cap will not be included in performance assessments
    max_market_cap: 999150_000_000  # coins above this market cap will not be included in performance assessments

    # Train/Test/Eval split
    test_size: 0.2  # what % of the total population will be used as test
    eval_size: 0.05  # what % used for the early stopping eval set



    # CoinModel Feature Selection
    # Params used to remove unnecessary features
    feature_selection:

        drop_patterns: [
            # Segment Category
            # all_wallets*,
            # score_quantile|*,
            # score_binary|*

            # Segment Family
            # score_binary|cw_return_rate_000*,
            # score_binary|cw_return_rate_005*,
            score_binary|cw_return_rate_025*,
            score_binary|cw_return_rate_040*,
            score_binary|net_gain_1000*,
            score_binary|cw_net_flows_1000*,

            # score_binary|cw_net_flows_1000*,
            # score_binary|net_gain_1000*,

            # Metric Detail
            '*|trading/crypto_cash_buys|*',
            '*|trading/crypto_cash_sells|*',
            '*|trading/crypto_inflows|*',
            '*|trading/crypto_net_cash_flows|*',
            '*|trading/crypto_net_flows|*',
            '*|trading/crypto_net_gain|*',
            '*|trading/crypto_outflows|*',
            '*|trading/max_investment|*',
            # '*|trading/total_volume|*',
            '*|trading/unique_coins_traded|*',
            # '*|trading/average_transaction|*',
            '*|balances/usd_balance_starting*|*',
            # '*|balances/usd_balance_ending*|*',


            # Transformation Base
            '*|*/cw_return_rate_regression_score*',
            '*|*/return_rate_regression_score*',
            '*|*cw_net_flows_1000_score*',
            '*|*/net_gain_1000_score*',
            '*|*/cw_return_rate_040_score*',
            '*|*/cw_return_rate_025_score*',
            '*|*/cw_return_rate_005_score*',
            '*|*/cw_return_rate_000_score*',

            # '*|score_dist/*',
            # '*|score_dist/*_median',
            # '*|score_dist/*_p05',
            # '*|score_dist/*_p10',
            # '*|score_dist/*_p90',
            # '*|score_dist/*_p95',
            # '*|score_dist/*_std',

            '*|score_wtd/*',

            # Transformation Method
            # '*/sum',
            # '*/sum_pct',
            '*/count',
            '*/count_pct',

            '*|*/*/kurt',
            '*|*/*/median',
            '*|*/*/p002',
            '*|*/*/p01',
            '*|*/*/p05',
            '*|*/*/p10',
            '*|*/*/p90',
            '*|*/*/p95',
            '*|*/*/p99',
            # '*|*/*/p998',
            '*|*/*/skew',
            '*|*/*/std',


        ]

        # Correlation/variance-based removal
        scale_before_selection: False # whether to apply variance thresholds before or after scaling data
        variance_threshold: 0.00 # features with this level of variance or less will be removed
        correlation_threshold: 1.999 # features above this correlation coefficient will be removed
        protected_features: []

    # CoinModel Params
    model_params:
        n_estimators: 400
        max_depth: 4
        min_child_weight: 10
        learning_rate: 0.02
        colsample_bytree: 1.0
        subsample: 1.0
        gamma: 0.02
        max_bin: 256
        early_stopping_rounds: 20
        eval_metric: rmse

        # non modeling metaparams
        random_state: 42
        n_jobs: -1

    # CoinModel Grid Search
    grid_search_params:

        #KeyParam Grid Search
        # -------------------------------
        # enabled: True
        # -------------------------------

        # Search Methodology
        drop_patterns_include_n_features: 1

        n_iter: 400  # random search limit
        n_splits: 5  # cv splits
        regressor_scoring: neg_root_mean_squared_error
        # classifier_scoring: validation_auc_scorer
        classifier_scoring: validation_top_percentile_returns_scorer
        percentile_threshold: 0.005

        build_post_search_model: False  # whether to build a model after the grid search
        verbose_level: 3  # scikit-learn verbosity


        # Params
        param_grid:

            # # Depth and Child Weight
            # estimator__max_depth: [3,4,5,6]
            # estimator__min_child_weight: [10,15,20,25]

            # Col/Row Sampling
            # estimator__subsample: [0.5, .6, .7, .8, .9, 1.0]
            # estimator__colsample_bytree: [0.9, 1.0]

            # # Model Speed
            # estimator__tree_method: [hist, approx, auto]
            # estimator__max_bin: [64, 128, 256]
            # estimator__gamma: [0.0, 0.1, 1.0]  # controls the minimum loss reduction needed to split a node

            # # Tree Training Speed Overrides
            # estimator__n_estimators: [150]
            # estimator__learning_rate: [0.02]

            # Optimize for Speed
            estimator__n_jobs: [4]  # how many models to build at once
            estimator__nthread: [4]  # how many threads each model can use
            # estimator__max_bin: [128]
            # estimator__tree_method: [hist]

            drop_columns__drop_patterns: [
                # Segment Category
                # all_wallets*,
                # score_quantile|*,
                # score_binary|*

                # Segment Family
                # score_binary|cw_return_rate_000*,
                # # score_binary|cw_return_rate_005*,
                # score_binary|cw_return_rate_025*,
                # # score_binary|cw_return_rate_040*,

                # Metrics
                # -------
                # '*|trading/average_transaction|*',
                # '*|trading/crypto_cash_buys|*',
                # '*|trading/crypto_cash_sells|*',
                # '*|trading/crypto_inflows|*',
                # '*|trading/crypto_net_cash_flows|*',
                # '*|trading/crypto_net_flows|*',
                # '*|trading/crypto_net_gain|*',
                # '*|trading/crypto_outflows|*',
                # '*|trading/max_investment|*',
                # # '*|trading/total_volume|*',
                # '*|trading/unique_coins_traded|*',
                # # '*|trading/average_transaction|*',
                # '*|balances/usd_balance_starting*|*',
                # # '*|balances/usd_balance_ending*|*',


                # # Transformation Base
                # '*|*/cw_return_rate_regression_score*',
                # '*|*/return_rate_regression_score*',
                # # '*|*/cw_return_rate_040_score*',
                # '*|*/cw_return_rate_025_score*',
                # '*|*/cw_return_rate_005_score*',
                # '*|*/cw_return_rate_000_score*',

                # # '*|score_dist/*',
                # # '*|score_dist/*_median',
                # # '*|score_dist/*_p05',
                # '*|score_dist/*_p10',
                # '*|score_dist/*_p90',
                # # '*|score_dist/*_p95',
                # # '*|score_dist/*_std',

                # '*|score_wtd/*',

                # '*/sum',
                # '*/sum_pct',
                # '*/count',
                # '*/count_pct',

                '*|score_dist/*/kurt',
                '*|score_dist/*/median',
                '*|score_dist/*/p002',
                '*|score_dist/*/p01',
                '*|score_dist/*/p05',
                '*|score_dist/*/p10',
                # '*|score_dist/*/p90',
                '*|score_dist/*/p95',
                # '*|score_dist/*/p99',
                # '*|score_dist/*/p998',
                '*|score_dist/*/skew',
                '*|score_dist/*/std',

            ]




    # Coin model workflow params
    score_name: net_gain_max_investment_winsorized_base  # reference name for feature columns etc


# CoinModel Multithreading
# Determines how many workers will be used in multithreading executions
n_threads: #CoinModel
    cw_flattening_threads: 24  # multithreads flattening in wallet_metrics_flattening.py
