market_timing:
  offsets:
    price_rsi_14:
      offsets: [14,30]
      retain_base_columns: False
    price_sma_7:
      offsets: [7,30]
      retain_base_columns: False
    volume_sma_7:
      offsets: [7,30]
      retain_base_columns: True
