# WalletModel Epochs Config
offset_epochs:
    # offsets: [0]
    # offsets: [85]
    # offsets: [0, -90, -180]
    offsets: [0, -60, -120, -180, -240, -300, -360] #, -450, -540]
    # offsets: [0, -50, -100, -150, -200, -250, -300] # , -400, -500]
    # offsets: [0, -50, -100, -150, -200, -250, -300, -350, -400, -450, -500]
    # validation_offsets: [30]
    # validation_offsets: [30, 60]
    validation_offsets: [30, 60, 90]
    # validation_offsets: [40, 70, 100]
    # validation_offsets: [30, 60, 90, 120, 150, 180]
    # validation_offsets: [85]
