# CheckpointValidation
# WalletModel Config
# Time series keyed on coin_id-date
time_series:
    market_data:
        price:
            indicators:
                sma:
                    parameters:
                        window: [2]
                # rsi:
                #     parameters:
                #         window: [7]
        volume:
            indicators:
                sma:
                    parameters:
                        window: [12]
        # mfi:
        #     indicators:
        #         sma:
        #             parameters:
        #                 window: [5]
        # obv:
        #     indicators:
        #         sma:
        #             parameters:
        #                 window: [5]


# Time series keyed on only date
macro_trends:
    btc_price:
        aggregations:
            first:
                scaling: "none"
            last:
                scaling: "none"
            std:
                scaling: "none"
        indicators:
            rsi:
                parameters:
                    window: [100]
                aggregations:
                    last:
                        scaling: "none"
    btc_mvrv_z_score:
        aggregations:
            first:
                scaling: "none"
            last:
                scaling: "none"
    global_market_cap:
        aggregations:
            first:
                scaling: "none"
            last:
                scaling: "none"
        indicators:
            rsi:
                parameters:
                    window: [100]
                aggregations:
                    last:
                        scaling: "none"
    global_volume:
        aggregations:
            first:
                scaling: "none"
            last:
                scaling: "none"