# CheckpointValidation
# WalletModel Config
# Time series keyed on coin_id-date
time_series:
    market_data:
        price:
            indicators:
                sma:
                    parameters:
                        window: [2]
                    rolling:
                        comparisons:
                            pct_change:
                                scaling: "None"
                        window_duration: 30
                        lookback_perios: 3
        volume:
            indicators:
                sma:
                    parameters:
                        window: [3]
                    rolling:
                        aggregations:
                            last:
                                scaling: "none"
                        comparisons:
                            pct_change:
                                scaling: "None"
                        window_duration: 30
                        lookback_periods: 3
        market_cap:
            indicators:
                sma:
                    parameters:
                        window: [3]
                    rolling:
                        aggregations:
                            last:
                                scaling: "none"
                        comparisons:
                            pct_change:
                                scaling: "None"
                        window_duration: 30
                        lookback_periods: 3


    # Time series keyed on only date
    macro_trends:
        btc_price:
            aggregations:
                first:
                    scaling: "none"
                last:
                    scaling: "none"
                std:
                    scaling: "none"
            indicators:
                rsi:
                    parameters:
                        window: [100]
                    aggregations:
                        last:
                            scaling: "none"
        btc_mvrv_z_score:
            aggregations:
                first:
                    scaling: "none"
                last:
                    scaling: "none"
        global_market_cap:
            aggregations:
                first:
                    scaling: "none"
                last:
                    scaling: "none"
            indicators:
                rsi:
                    parameters:
                        window: [100]
                    aggregations:
                        last:
                            scaling: "none"
        global_volume:
            aggregations:
                first:
                    scaling: "none"
                last:
                    scaling: "none"