# WalletModel Epochs Config
offset_epochs:
    offsets: [0]
    # offsets: [0, -90, -180, -270]
    # offsets: [0, -50, -100, -200, -300, -400, -500]
    # offsets: [0, -50, -100, -150, -200, -250, -300, -350, -400, -450, -500]
    # validation_offsets: [0, 30, 60, 90]
