# Params in this config will be used to override the normal wallets_config.yaml.

# WalletModel Modeling Config
modeling:

    # Which wallet performance metric to use as the target variable.
    target_variable: [
        "crypto_net_gain/max_investment/winsorized",
        "crypto_net_gain/max_investment/base"
    ]
